server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
#          uri: https://github.com/lynnlovemin/SpringCloudLesson.git #配置git仓库地址
          uri: https://github.com/ligexiaowht/SpringcloudConfig.git
          searchPaths: repo/ #配置仓库路径
#          username: lynnlovemin #访问git仓库的用户名
#          password: ****** #访问git仓库的用户密码
      label: master #配置仓库的分支
  rabbitmq:
    host: 192.168.60.55
    port: 5672
    username: tom
    password: 123456
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
